[project]
name = "part-b-scraper"
version = "0.1.0"
description = "Scrapes Part B Fee Schedules"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "pandas>=2.2.3",
    "pdfplumber>=0.11.5",
    "pytest>=8.3.4",
    "requests>=2.32.3",
]
