name: Build

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: '1.4.0'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
      - name: CI (format, lint, test)
        run: just build
